name: Build and Deploy Azure Functions

on:
  push:
    branches:
      - main  # Or your desired branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # or the Node.js version you are using

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # (Optional) Run tests or build steps if you have any
      - name: Run Tests
        run: npm test

       # Log in to Azure using the credentials stored in the repository secrets.
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy to Azure Functions
      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        with:
          app-name: 'FluffyFunctionsAPI'  # Your Azure Function App name
          package: '.'  # Package root; adjust if needed
